### ISSUE TITLE
Crash on startup with new 1.8.9 version

### ISSUE THREAD

**Issue by kwpugh** [BinaryCrafter/StorageSilo#24]
Client crashes on single player startup.

Crash report:   http://pastebin.com/raw/hJTGGTMZ

**Comment by BinaryCrafter** [comment]
Thanks for the report. I can see what's happening, but I've no idea why. It's definitely StorageSilo that's crashing, but I'm not sure the problem is actually due to StorageSilo.

I'm guessing another mod you have installed is somehow interfering with the Material types in the game. I'll have to try and replicate the mods you have and work out what's causing this, but leave it with me, I'll provide an update as soon as I've worked out what's going on.

**Comment by kwpugh** [comment]
Here is a link to my modpack on Technic:  http://www.technicpack.net/modpack/pughland-neoteric.799560

**Comment by BinaryCrafter** [comment]
It's okay, I've figured it out. I've stupidly uploaded the wrong build. Please remove the mod, I'll re-upload the correct version very soon! My apologies!

**Comment by BinaryCrafter** [comment]
Okay, new version uploading now. I tried to shortcut the upgrade of my dev environment to 1.8.9 and it didn't work. Just uploaded a new build to curse just now that should resolve this. Thanks for reporting.
