### ISSUE TITLE
Duping items in Crafting Silo

### ISSUE THREAD

**Issue by kwpugh** [BinaryCrafter/StorageSilo#25]
One of my players pointed out that he point items in the crafting grid and shift-clicked the result into the silo and the items in the grid remained.   He then could left-click an item in the receipt and replace it and repeat the process.

After doing all the duping he wanted, he could retrieve the items from the grid (same amount he started with).

Thought you should know.

**Comment by BinaryCrafter** [comment]
Thanks for the report, but can you confirm what version of the mod is being used (and that they are the same version on the server and client)? This exact issue was corrected  was corrected a few weeks ago. See https://github.com/BinaryCrafter/StorageSilo/issues/18 for details. The most recent version released on Curse should not be affected by this.

I'll close this for now as I believe it's resolved already, but if you confirm the version number, and it's still affecting the current version, then I'll re-open this ticket and investigate.

**Comment by kwpugh** [comment]
I'm using the last stable release (1.2.0) on client and server).   Was it fixed in the beta release 1.2.2?  BTW: I'm running this on 1.7.10.

**Comment by BinaryCrafter** [comment]
Ahh, that makes sense. 1.7.10-1.2.2 was still set to beta (my mistake, I thought I'd set all *-1.2.2 releases to stable). I've updated it on curse now, so you should shortly see your client prompt you to update the mod to 1.7.10-1.2.2 (assuming you use Curse Voice to obtain your mods).

This is definitely fixed in 1.7.10-1.2.2, apologies for the confusion :)
